#!/bin/bash
#SBATCH --job-name=network_test
#SBATCH --output=experiments/logs/%x_%j.out
#SBATCH --error=experiments/logs/%x_%j.err
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=48G
#SBATCH --time=02:00:00
#SBATCH --gres=gpu:1

#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=paula.banares@iac.es

# Clean environment
module purge 2>/dev/null
# Source Conda from your scratch directory
source /scratch/paulabp/miniconda3/etc/profile.d/conda.sh
# Activate your environment
conda activate tfm_conda_venv

cd "/scratch/paulabp/TFM/repository/Deep_Fast_CAM/unsupervisedMFBD-separate_blocks"

srun python -u comprobacion_50.py 