#!/bin/bash
#SBATCH --job-name=tiff_img_deconv_NOT
#SBATCH --output=experiments/logs/%x_%j.out
#SBATCH --error=experiments/logs/%x_%j.err
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=24G
#SBATCH --time=16:00:00
#SBATCH --gres=gpu:1
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=paula.banares@iac.es

source /home/paulabp/miniconda3/etc/profile.d/conda.sh
conda activate tfm_conda_venv

srun python tiff_img_deconv_NOT.py