#!/bin/bash
#SBATCH --job-name=tiff_img_deconv_CS
#SBATCH --output=experiments/logs/%x_%j.out
#SBATCH --error=experiments/logs/%x_%j.err
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=24G
#SBATCH --time=16:00:00
#SBATCH --gres=gpu:1
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=paula.banares@iac.es

module load cuda/12.1 2>/dev/null || true

conda activate tfm_conda_venv

python tiff_img_deconv_CS.py 